# Generated by Django 4.2.4 on 2023-08-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='country1',
            field=models.CharField(max_length=250),
        ),
    ]
