# Generated by Django 4.2.4 on 2023-08-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristic',
            field=models.CharField(default='TDM Technology', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristic_description',
            field=models.TextField(default='default_description'),
        ),
    ]
